# Generated by Django 5.0.3 on 2024-04-04 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('topic_id', models.CharField(max_length=255)),
                ('gyroscopeX', models.FloatField(null=True)),
                ('gyroscopeY', models.FloatField(null=True)),
                ('gyroscopeZ', models.FloatField(null=True)),
                ('accelerometerX', models.FloatField(null=True)),
                ('accelerometerY', models.FloatField(null=True)),
                ('accelerometerZ', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('assigned_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
