# Generated by Django 5.0.3 on 2024-04-15 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('score', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('path', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAttributes',
            fields=[
                ('atr', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('nif', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('topic_id', models.CharField(max_length=255)),
                ('message', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientSensor',
            fields=[
                ('idSensor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_id_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('idSensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move_id_app.patientsensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
