# Generated by Django 5.0.3 on 2024-03-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('move_id_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='patiente',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Patiente',
        ),
    ]
